### ISSUE TITLE
ToolAgent调用随机数生成函数出现问题

### ISSUE THREAD

**Issue by xukache** [zlai-llm/zlai#2]
之前使用glm4-0520调用这个随机数生成函数会出现不调用工具的情况，现在更换为glm4-flash模型，代码如下：
![image](https://github.com/user-attachments/assets/d02fbfc0-525a-4520-a60a-f14e92ef525b)
报错如下：
![image](https://github.com/user-attachments/assets/7b635f62-ac1f-4272-b1bb-64b29c1aa3f1)
原因分析：
![image](https://github.com/user-attachments/assets/df95f01f-d09c-46d4-9673-2a544da1fb59)
随机数生成函数返回的是int类型，而数据验证函数这里使用了len()函数，导致报错：
![image](https://github.com/user-attachments/assets/7d4f15ce-bf9e-4d3e-83b1-add77285e70d)

**Comment by CaoChensy** [comment]
在#1中已经解决了。
