### ISSUE TITLE
ToolAgent调用函数问题

### ISSUE THREAD

**Issue by xukache** [zlai-llm/zlai#3]
代码如下：
![image](https://github.com/user-attachments/assets/48beda29-5216-4661-8925-5105df93f6f2)
报错如下：
![image](https://github.com/user-attachments/assets/fff8faa8-2aa6-48f3-a948-03fad72adaef)
直接将`task_completion.memory_messages`复制出来运行结果没有问题
![image](https://github.com/user-attachments/assets/992a6a6d-dfb4-4195-831c-1627bc49b885)
![image](https://github.com/user-attachments/assets/1803a0a2-f2a0-471b-9c4a-e65a13a604f3)
结果如下：
![image](https://github.com/user-attachments/assets/c24d14c0-022e-4c08-a3c5-39f8f4d6b73c)

**Comment by CaoChensy** [comment]
在#1中已经解决了，如果还有问题，请再提issue。
可以安装master分支
pip install git+https://github.com/zlai-llm/zlai.git
